name: Small Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Test
      run: npm test

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to staging
      run: |
        # Your deployment commands here
        echo "Deploying to staging..."

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to production
      run: |
        # Your deployment commands here
        echo "Deploying to production..."

  notify:
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Send notification
      run: |
        # Your notification logic here
        echo "Workflow completed successfully!"
