name: Small Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Your build commands here
          echo "Building..."

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          # Your test commands here
          echo "Testing..."

  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to staging
        run: |
          # Your deployment commands for staging here
          echo "Deploying to staging..."

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          # Your deployment commands for production here
          echo "Deploying to production..."

  notify:
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send notification
        run: |
          # Your notification logic here
          echo "Workflow completed successfully!"
